<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'category_id' => 1,
                'sku' => 'BWBOM',
                'name' => 'Bawang Bombai',
                'buy_price' => 18500,
                'sell_price' => 25000,
                'stock' => 20,
                'unit' => 'KG',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'BWM',
                'name' => 'Bawang Merah',
                'buy_price' => 27000,
                'sell_price' => 30000,
                'stock' => 10,
                'unit' => 'KG',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'BWP',
                'name' => 'Bawang Putih',
                'buy_price' => 27000,
                'sell_price' => 30000,
                'stock' => 19,
                'unit' => 'KG',
                'is_active' => 1,
            ],
            [
                'category_id' => 2,
                'sku' => 'BJWJN',
                'name' => 'Biji Wijen',
                'buy_price' => 50000,
                'sell_price' => 53000,
                'stock' => 10,
                'unit' => 'KG',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'DESBUKBAL',
                'name' => 'Desaku Bubuk Balado 25gr',
                'buy_price' => 22000,
                'sell_price' => 23000,
                'stock' => 1,
                'unit' => 'RENCENG',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'DESKET15GR',
                'name' => 'Desaku Ketumbar E1000 15gr',
                'buy_price' => 9500,
                'sell_price' => 12000,
                'stock' => 2,
                'unit' => 'RENCENG',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'DESKUN10GR',
                'name' => 'Desaku Kunyit 10gr',
                'buy_price' => 9500,
                'sell_price' => 12000,
                'stock' => 2,
                'unit' => 'RENCENG',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'DESMAR12.5',
                'name' => 'Desaku Marinasi New 12.5gr',
                'buy_price' => 10000,
                'sell_price' => 12000,
                'stock' => 8,
                'unit' => 'RENCENG',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'GRMBT',
                'name' => 'Garam Bata',
                'buy_price' => 10000,
                'sell_price' => 12000,
                'stock' => 2,
                'unit' => 'PCS',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'GRMBE',
                'name' => 'Garam Segitiga Emas',
                'buy_price' => 1341,
                'sell_price' => 70000,
                'stock' => 220,
                'unit' => 'PCS',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'GRMLBLB',
                'name' => 'Garam Laba-Laba',
                'buy_price' => 3200,
                'sell_price' => 3500,
                'stock' => 100,
                'unit' => 'PCS',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'JAH',
                'name' => 'Jahe',
                'buy_price' => 17000,
                'sell_price' => 20000,
                'stock' => 10,
                'unit' => 'KG',
                'is_active' => 1,
            ],
            [
                'category_id' => 3,
                'sku' => 'KCIJO',
                'name' => 'Kacang Ijo',
                'buy_price' => 28000,
                'sell_price' => 29000,
                'stock' => 25,
                'unit' => 'KG',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'KCPSED725GR',
                'name' => 'Kecap Sedap 725gr',
                'buy_price' => 20000,
                'sell_price' => 22000,
                'stock' => 5,
                'unit' => 'PCS',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'KMR',
                'name' => 'Kemiri',
                'buy_price' => 41000,
                'sell_price' => 45000,
                'stock' => 25,
                'unit' => 'KG',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'KTMBRBJ',
                'name' => 'Ketumbar Biji',
                'buy_price' => 32000,
                'sell_price' => 35000,
                'stock' => 5,
                'unit' => 'KG',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'KTMBRBBK',
                'name' => 'Ketumbar Bubuk',
                'buy_price' => 32000,
                'sell_price' => 35000,
                'stock' => 5,
                'unit' => 'KG',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'BKGPW',
                'name' => 'Koepoe Baking Powder 45gr',
                'buy_price' => 5833,
                'sell_price' => 7000,
                'stock' => 6,
                'unit' => 'PCS',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'LDBJ',
                'name' => 'Lada Biji',
                'buy_price' => 168000,
                'sell_price' => 170000,
                'stock' => 5,
                'unit' => 'KG',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'LDM2.5',
                'name' => 'Ladaku Merica Bubuk 2.5 gr',
                'buy_price' => 9500,
                'sell_price' => 11000,
                'stock' => 9,
                'unit' => 'RENCENG',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'LGKS',
                'name' => 'Lengkoas',
                'buy_price' => 5000,
                'sell_price' => 8000,
                'stock' => 10,
                'unit' => 'KG',
                'is_active' => 1,
            ],
            [
                'category_id' => 4,
                'sku' => 'MMLM610',
                'name' => 'Mama Lemon Nipis 610ml',
                'buy_price' => 8925,
                'sell_price' => 10000,
                'stock' => 12,
                'unit' => 'PCS',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'MMY1KG',
                'name' => 'Mamayo Mayones 1kg',
                'buy_price' => 22083,
                'sell_price' => 24000,
                'stock' => 12,
                'unit' => 'PCS',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'MMYMEN500',
                'name' => 'Mamayo Mentai 500gr',
                'buy_price' => 24000,
                'sell_price' => 26000,
                'stock' => 5,
                'unit' => 'PCS',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'MASAY123GR',
                'name' => 'Masako Ayam 123gr',
                'buy_price' => 4396,
                'sell_price' => 5000,
                'stock' => 48,
                'unit' => 'PCS',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'MASAY1KG',
                'name' => 'Masako Ayam 1kg',
                'buy_price' => 31920,
                'sell_price' => 36000,
                'stock' => 25,
                'unit' => 'PCS',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'MASAY8.5GR',
                'name' => 'Masako Ayam 8.5gr',
                'buy_price' => 4433,
                'sell_price' => 5000,
                'stock' => 60,
                'unit' => 'RENCENG',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'PLM200',
                'name' => 'Palmia 200gr',
                'buy_price' => 6000,
                'sell_price' => 7000,
                'stock' => 120,
                'unit' => 'PCS',
                'is_active' => 1,
            ],
            [
                'category_id' => 5,
                'sku' => 'SST1LT',
                'name' => 'Saori Saos Tiram 1 Liter',
                'buy_price' => 52000,
                'sell_price' => 55000,
                'stock' => 6,
                'unit' => 'BTL',
                'is_active' => 1,
            ],
            [
                'category_id' => 5,
                'sku' => 'SDELMEXH1KG',
                'name' => 'Saos Del Monte Extra Hot 1kg',
                'buy_price' => 23150,
                'sell_price' => 24000,
                'stock' => 50,
                'unit' => 'PCS',
                'is_active' => 1,
            ],
            [
                'category_id' => 5,
                'sku' => 'SDELTOM1KG',
                'name' => 'Saos Del Monte Tomat 1kg',
                'buy_price' => 17800,
                'sell_price' => 19000,
                'stock' => 50,
                'unit' => 'PCS',
                'is_active' => 1,
            ],
            [
                'category_id' => 5,
                'sku' => 'STER1LT',
                'name' => 'Saos Teriaki 1ltr',
                'buy_price' => 52000,
                'sell_price' => 54000,
                'stock' => 6,
                'unit' => 'BTL',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'SAE1',
                'name' => 'Sasa E1000 14gr',
                'buy_price' => 17708,
                'sell_price' => 19000,
                'stock' => 12,
                'unit' => 'PACK',
                'is_active' => 1,
            ],
            [
                'category_id' => 1,
                'sku' => 'SAE2',
                'name' => 'Sasa E2000',
                'buy_price' => 36042,
                'sell_price' => 37000,
                'stock' => 12,
                'unit' => 'PACK',
                'is_active' => 1,
            ],
            [
                'category_id' => 3,
                'sku' => 'TLR',
                'name' => 'Telur Ayam',
                'buy_price' => 24000,
                'sell_price' => 25000,
                'stock' => 45,
                'unit' => 'KG',
                'is_active' => 1,
            ],
            [
                'category_id' => 6,
                'sku' => 'TPGC1KG',
                'name' => 'Tepung Cakra 1kg',
                'buy_price' => 11000,
                'sell_price' => 12000,
                'stock' => 60,
                'unit' => 'PCS',
                'is_active' => 1,
            ],
            [
                'category_id' => 6,
                'sku' => 'TPGMAI1KG',
                'name' => 'Tepung Maizena 1kg',
                'buy_price' => 21667,
                'sell_price' => 24000,
                'stock' => 18,
                'unit' => 'KG',
                'is_active' => 1,
            ],
            [
                'category_id' => 6,
                'sku' => 'TPGPNR',
                'name' => 'Tepung Panir',
                'buy_price' => 13500,
                'sell_price' => 14000,
                'stock' => 30,
                'unit' => 'KG',
                'is_active' => 1,
            ],
            [
                'category_id' => 6,
                'sku' => 'TPGRS500GR',
                'name' => 'Tepung Rosebrand 500gr',
                'buy_price' => 8400,
                'sell_price' => 9500,
                'stock' => 20,
                'unit' => 'PCS',
                'is_active' => 1,
            ],
            [
                'category_id' => 6,
                'sku' => 'TPGSJ',
                'name' => 'Tepung Sajiku 900gr',
                'buy_price' => 24063,
                'sell_price' => 25000,
                'stock' => 80,
                'unit' => 'KG',
                'is_active' => 1,
            ],
            [
                'category_id' => 6,
                'sku' => 'TSS70GR',
                'name' => 'Tepung Sasa Serbaguna 70GR',
                'buy_price' => 22500,
                'sell_price' => 23000,
                'stock' => 12,
                'unit' => 'RENCENG',
                'is_active' => 1,
            ],
            [
                'category_id' => 6,
                'sku' => 'SGTGBR',
                'name' => 'Tepung Terigu Segitiga Biru Kemasan 1KG',
                'buy_price' => 10583,
                'sell_price' => 11000,
                'stock' => 60,
                'unit' => 'PCS',
                'is_active' => 1,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
